### ISSUE TITLE
migrate project from spring boot 2 -> 3

### ISSUE THREAD

**Issue by AmitSureshChandra** [AmitSureshChandra/online-code-runner#17]
commit for the change : https://github.com/AmitSureshChandra/online-compiler/commit/ef3bc432674703ea54d124ad5a7b8ff801eceb98

**Comment by Shiroo77** [comment]
Is the issue solved ? I would like to work on this

**Comment by AmitSureshChandra** [comment]
> Is the issue solved ? I would like to work on this

@Shiroo77 I have already added spring boot 3 in current project, I forgot to update the issue, 
commit for that change : ef3bc43

I have used `online-compiler` api  in `code-judge` project. `code-judge` is currently in spring boot 2, so if you want migrate that project in spring boot 3.

link for that issue : https://github.com/AmitSureshChandra/code-judge/issues/12
